name: Release
on:
  workflow_call:

jobs:
  complete:
    name: Merge PR
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for Release PR
        run: gh pr merge "$PR_URL" --auto --merge
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
