name: Deploy to Github Pages
on:
  workflow_call:

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    name: Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.x
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Install
        run: npm ci
      - name: Deploy
        run: npm run deploy
