name: Main pre build
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR merged by $ACTOR"
        env:
          ACTOR: ${{ github.actor }}
