name: Milestone Release
on:
  milestone:
    types:
      - closed

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'

jobs:
  test:
    name: QA
    uses: ./.github/workflows/job.test.yaml
  build:
    name: Build
    needs:
      - test
    uses: ./.github/workflows/job.build.yaml
  release:
    name: Release
    needs:
      - test
      - build
    uses: ./.github/workflows/job.release.yaml
    with:
      release_type: milestone
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_APP_TOKEN }}
